### ISSUE TITLE
Bug with sandbox API security tests always returning success (200) even if token is blank

### ISSUE THREAD

**Issue by Axzyl** [questsin/UBC-Rogers-CAMARA-Hackathon#15]
# Team Raid6

In the sandbox API tests, there is an issue with the security tests - as shown below, the top test (for testing if the number/token match) has a different assert case than the bottom test (a negative test with a blank token)

![image](https://github.com/user-attachments/assets/afaaade4-5611-42e7-81ee-a11fcb52b7d4)

When testing with replacing the token with a blank token in the top case, the top case still works. Should the top case be replaced with `response.data.status` instead of `response.status`?

**Comment by questsin** [comment]
http status codes are different from status code returned in the body. This hasn't been standardized yet.

This means the http call returned 200, as the server was up. the Backend handled the call. API exit codes are different.
